N_TRIALS_TRAINING: 25
N_TRIALS_EXPERIMENT: 50
EXPNUM: 10
BACKGROUND_COLOR: #827c7c
FRAME_RATE: 60
SCREEN_RES: [1440, 900]
FIX_CROSS_COLOR: #000000
STIM_TIME: 15
REACTION_TIME: 90
REACTION_KEYS: [3,4,8,9]
NEUT_TEXT: ######
